# .bashrc
export PYTHONPATH=~/soft/packages/Python-3.7.3/lib/python3.7/site-packages:$PYTHONPATH
# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
. ~/.bash_rouleau
